### ===========================
### Auth API Tests
### ===========================
 
@baseUrl = http://localhost:3000/api/auth
 
 
### -----------------------------------------------
### 1. Register
### -----------------------------------------------
POST {{baseUrl}}/register
Content-Type: application/json
 
{
    "name": "Kyu Won",
    "email": "kyuwon@example.com",
    "password": "Password123!",
    "confirmPassword": "Password123!"
}
 
### -----------------------------------------------
### 2. Login
### -----------------------------------------------
# @name login
POST {{baseUrl}}/login
Content-Type: application/json
 
{
    "email": "user@example.com",
    "password": "Password123!"
}
 
### -----------------------------------------------
### 3. Refresh Token
### -----------------------------------------------
POST {{baseUrl}}/refresh
Cookie: refresh_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzY2YWI4OC05ODE3LTRiZWYtYmI2MC0yNDQ5OWQ5YWZlYWIiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc3NjU2MzQ5OSwiZXhwIjoxNzc3MTY4Mjk5fQ.oolNHcaGtW5dc1VfhTp_zUG5vfrDQgqPku8T9c6ZXTsHEeX9dS3LwLBO108cGHqw879vv5JvUXJ8P_MH-6rM6hllFW1kDskJ1e8Mz5vtxVskEAdvTB6Qn0LUrcWLDI8t4jtOKzVES7op8rPqGxu7XfycC49CxnPIUc9fx4PhSpt6n4v2oGrsgP8dGggy2amj2MJAv8cnQpVsyWKuDjmZ2UjY7kBFoRO6lmA17DP9bnqslmuApsgMMvTt10Hgs0xq3NcQuUJAkwlOAlN-eHMMp0_y9_cnIez2cVhr_-2vjXSe5SGfzu-5fN0RZzonMOoVqI0pygz4b6HdbBsn4vQuVg;

### -----------------------------------------------
### 4. Logout
### -----------------------------------------------
# @name logout
POST {{baseUrl}}/logout
Authorization: Bearer {{login.response.body.accessToken}}
 
### -----------------------------------------------
### 5. Verify Password
### -----------------------------------------------
# @name verifyPassword
POST {{baseUrl}}/verify-password
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json
 
{
    "currentPassword": "Password456!"
}
 
### -----------------------------------------------
### 6. Change Password
### -----------------------------------------------
PATCH {{baseUrl}}/change-password
Authorization: Bearer {{login.response.body.accessToken}}
Cookie: password_change_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYzY2YWI4OC05ODE3LTRiZWYtYmI2MC0yNDQ5OWQ5YWZlYWIiLCJ0eXBlIjoicGFzc3dvcmQtY2hhbmdlIiwiaWF0IjoxNzc2NTYzNTUyLCJleHAiOjE3NzY1NjM4NTJ9.R48AHNx-P2xlZM0_66nSdNT-ra0jEV5IMYNkE_PJYXCCD6JEh3hU7zTNs8In9PTPbGz-gxhb_pzu9yhKS119ikzQZcDH-odPor6rBetuumB0fvDOYhQSJ9xCzJJjq5fVAlvP4ZmWbAh4_aUYq-8y4zMsjFGtcGMgdLNeVovRz9Q5bReOjKh16f52UIYETuOT1q5Np3LXNIwxyrYPQSTNwV1fTgD5dMSf5zO0YbyBNm2h9iKcDkG0O6UL_0ntd_DInqGafru2MPvCgiYR1O8oV5CGSRDw-89GjI6BWNlEolgdIASKxwPHrvdfbc7640UGpJgY_z7Mh6dx1Jp4RgYz0Q
Content-Type: application/json
 
{
    "newPassword": "Password123!",
    "confirmPassword": "Password123!"
}
 